### PR TITLE
Added support for `$ref`:

### PR DESCRIPTION
**Pull request by tjlytle**
- Serve the reference base.
- Add reference to config.
- Allow base to be defined.

### CODE REVIEW

**Comment by borisirota** [comment]
Thanks for the PR ! I'm not using this module for more than a year. Would you like me to add you as a collaborator ?

**Comment by tjlytle** [comment]
Not sure what else I'll be adding, but that's fine by me. :+1:

**Comment by borisirota** [comment]
I added you as collaborator to this repository. Whats your npm username so I can give you access to that as well ?

**Comment by tjlytle** [comment]
@borisirota `tjlytle`

**Comment by borisirota** [comment]
@tjlytle I added you. thanks :)

**Comment by paxos** [comment]
This is very useful. Can you do a release with that?

**Comment by tjlytle** [comment]
@paxos Sorry for the delay, will try to get to that this week.

**Pull request merged**
